"""auto migration

Revision ID: 7cc38472588e
Revises: 998d3ca3cb58
Create Date: 2026-03-30 17:23:13.997491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc38472588e'
down_revision: Union[str, Sequence[str], None] = '998d3ca3cb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_spotlight', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_spotlight')
    # ### end Alembic commands ###
