"""auto migration

Revision ID: 998d3ca3cb58
Revises: 899ed8e39e12
Create Date: 2026-03-30 15:50:20.721052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998d3ca3cb58'
down_revision: Union[str, Sequence[str], None] = '899ed8e39e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_spotlight', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_spotlight')
    # ### end Alembic commands ###
